// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using WebAPI.Data.Validators;

namespace WebAPI.Data.Models;

public class Department
{
    [Key]
    public int Id { get; set; }

    [UniqueDepartmentName]
    [StringLength(20)]
    public string Name { get; set; } = null!;

    [StringLength(20)]
    public string? ManagerName { get; set; }

    [StringLength(50)]
    public string? Location { get; set; }

    [DepartmentOpenDate]
    public DateTime OpenDate { get; set; }

    //Navigation Property
    public virtual ICollection<Student> Students { get; set; } = new HashSet<Student>();
}