// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using WebAPI.Data.Validators;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Data.Models;


public class Student
{
    [Key]
    public int SSN { get; set; }

    [StringLength(30)]
    [RegularExpression("[a-zA-Z ]{3,30}", ErrorMessage = "Only letters and spaces are allowed.")]
    public string Name { get; set; } = null!;

    [Range(17, 35, ErrorMessage ="Age must be between 17 and 35")]
    public int Age { get; set; }

    [StringLength(30)]
    public string? Address { get; set; }

    [StringLength(100)]
    public string? ImageURL { get; set; }

    [StringLength(30)]
    [EmailAddress]
    [UniqueEmail] // Custom validation attribute to ensure email uniqueness
    public string Email { get; set; }

    [ForeignKey("Department")]
    public int? DepartmentId { get; set; }

    //Navigation Property
    public virtual Department? Department { get; set; }
}