// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using WebAPI.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace WebAPI.Data.Context;

public class UniversityContext : IdentityDbContext<ApplicationUser>
{
    public virtual DbSet<Student> Students { get; set; }
    public virtual DbSet<Department> Departments { get; set; }

    public UniversityContext(DbContextOptions dbContextOptions): base(dbContextOptions)
    {
        
    }

}